KMGamesCore.Web/Areas/Admin/Controllers/PlayerTypesController.cs
using KMGamesCore.Data.Repository.Interfaces;
using KMGamesCore.Models.Models;
using Microsoft.AspNetCore.Mvc;

namespace KMGamesCore.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PlayerTypesController : Controller
    {
        //----------PROPERTIES----------//

        private readonly IUnitOfWork _unitOfWork;

        //----------CONSTRUCTOR----------//

        public PlayerTypesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //----------ACTIONS----------//

        public IActionResult Index()
        {
            var types = _unitOfWork.PlayerTypes.GetAll();

            return View(types);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PlayerType playerType)
        {
            if (!ModelState.IsValid)
            {
                return View(playerType);
            }

            if (_unitOfWork.PlayerTypes.Exist(playerType))
            {
                ModelState.AddModelError(string.Empty, "There already exist a player type with that name.");

                return View(playerType);
            }

            _unitOfWork.PlayerTypes.Add(playerType);
            _unitOfWork.SaveChanges();

            TempData["SUCCESS"] = "Player Type added successfully";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if(id is null || id <= 0)
            {
                return NotFound();
            }

            PlayerType type = _unitOfWork.PlayerTypes.Get(t => t.PlayerTypeId == id);

            if(type is null)
            {
                return NotFound();
            }

            return View(type);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PlayerType playerType)
        {
            if (!ModelState.IsValid)
            {
                return View(playerType);
            }

            if (_unitOfWork.PlayerTypes.Exist(playerType))
            {
                ModelState.AddModelError(string.Empty, "There already exist a player type with that name.");

                return View(playerType);
            }

            _unitOfWork.PlayerTypes.Update(playerType);
            _unitOfWork.SaveChanges();

            TempData["SUCCESS"] = "Player Type edited successfully";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if(id is null || id <= 0)
            {
                return NotFound();
            }

            PlayerType type = _unitOfWork.PlayerTypes.Get(t => t.PlayerTypeId == id);

            if(type is null)
            {
                return NotFound();
            }

            if (_unitOfWork.PlayerTypes.ItsRelated(type))
            {
                TempData["Error"] = "Can't be deleted because it has related games";

                return RedirectToAction("Index");
            }

            return View(type);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete (PlayerType playerType)
        {
            if (!_unitOfWork.PlayerTypes.Exist(playerType.PlayerTypeId))
            {
                return NotFound();
            }

            _unitOfWork.PlayerTypes.Delete(playerType);
            _unitOfWork.SaveChanges();

            TempData["WARNING"] = "Player Type was deleted";

            return RedirectToAction("Index");
        }
    }
}

KMGamesCore.Web/Areas/Admin/Views/PlayerTypes/Create.cshtml
@using KMGamesCore.Models.Models
@model PlayerType

@{
    ViewData["title"] = "Create";
}

<div class="container-fluid justify-content-center w-50">

    <form method="post" asp-controller="PlayerTypes" asp-action="Create">
        <div class="shadow rounded-4 p-4">

            <h2>New Player Type</h2>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Type" class="form-label"></label>
                <input type="text" asp-for="Type" class="form-control w-50"/>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group d-flex justify-content-between mt-4">
            <button type="submit" class="btn btn-outline-primary w-25">
                <i class="bi bi-check2"></i>
            </button>
            <a asp-controller="PlayerTypes" asp-action="Index" class="btn btn-outline-danger w-25">
                <i class="bi bi-x-lg"></i>
            </a>
        </div>
    </form>

</div>
@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }

}

KMGamesCore.Web/Areas/Admin/Views/PlayerTypes/Delete.cshtml
@using KMGamesCore.Models.Models
@model PlayerType

@{
    ViewData["title"] = "Delete";
}

<div class="container-fluid justify-content-center w-50">

    <form method="post" asp-controller="PlayerTypes" asp-action="Delete">
        <div class="shadow rounded-4 p-4">

            <h2>Delete Player Type</h2>

            <input asp-for="PlayerTypeId" type="hidden"/>
            <input asp-for="RowVersion" type="hidden"/>

            <div class="form-group">
                <label asp-for="Type" class="form-label"></label>
                <input type="text" asp-for="Type" class="form-control w-50" readonly />
            </div>
        </div>
        <div class="form-group d-flex justify-content-between mt-4">
            <button type="submit" class="btn btn-outline-primary w-25">
                <i class="bi bi-check2"></i>
            </button>
            <a asp-controller="PlayerTypes" asp-action="Index" class="btn btn-outline-danger w-25">
                <i class="bi bi-x-lg"></i>
            </a>
        </div>
    </form>

</div>

KMGamesCore.Web/Areas/Admin/Views/PlayerTypes/Edit.cshtml
@using KMGamesCore.Models.Models
@model PlayerType

@{
    ViewData["title"] = "Edit";
}

<div class="container-fluid justify-content-center w-50">

    <form method="post" asp-controller="PlayerTypes" asp-action="Edit">
        <div class="shadow rounded-4 p-4">

            <h2>Edit Player Type</h2>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="PlayerTypeId" type="hidden"/>
            <input asp-for="RowVersion" type="hidden"/>

            <div class="form-group">
                <label asp-for="Type" class="form-label"></label>
                <input type="text" asp-for="Type" class="form-control w-50" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group d-flex justify-content-between mt-4">
            <button type="submit" class="btn btn-outline-primary w-25">
                <i class="bi bi-check2"></i>
            </button>
            <a asp-controller="PlayerTypes" asp-action="Index" class="btn btn-outline-danger w-25">
                <i class="bi bi-x-lg"></i>
            </a>
        </div>
    </form>

</div>
@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }

}

KMGamesCore.Web/Areas/Admin/Views/PlayerTypes/Index.cshtml
@using KMGamesCore.Models.Models
@model IEnumerable<PlayerType>

@{
    ViewData["title"] = "Index";
}

<div class="container-fluid justify-content-center w-75">

    <div class="d-flex justify-content-between">
        <h2>Player Types</h2>
        <div>
            <a asp-controller="PlayerTypes" asp-action="Create" class="btn btn-outline-primary">
                <i class="bi bi-plus-lg"></i>
            </a>
        </div>
    </div>
    <div>
        <table class="table">
            <thead>
                <tr class="table-primary">
                    <th>
                        Player Types
                    </th>
                    <th class="text-end">
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                @foreach(PlayerType type in Model)
                {
                    <tr class="table-dark">
                        <td valign="middle">@type.Type</td>
                        <td align="right">
                            <a asp-controller="PlayerTypes" asp-action="Edit"  asp-route-id="@type.PlayerTypeId"
                                class="btn btn-outline-warning rounded-circle pt-1 pb-1 pe-2 ps-2">
                                 <i class="bi bi-brilliance"></i>
                            </a>
                            <a asp-controller="PlayerTypes" asp-action="Delete" asp-route-id="@type.PlayerTypeId"
                               class="btn btn-outline-danger ms-2 rounded-circle pt-1 pb-1 pe-2 ps-2">
                                <i class="bi bi-x-lg"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>