KMGamesCore.Web/Areas/Admin/Controllers/CountriesController.cs
using KMGamesCore.Data.Repository.Interfaces;
using KMGamesCore.Models.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace KMGamesCore.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CountriesController : Controller
    {
        //----------PROPERTIES----------//

        private readonly IUnitOfWork _unitOfWork;

        //----------CONSTRUCTOR----------//

        public CountriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //----------ACTIONS----------//

        public IActionResult Index()
        {
            var countries = _unitOfWork.Countries.GetAll();

            return View(countries);
        }

        public IActionResult IndexDTable()
        {
            return View();
        }

        #region CREATE

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Country country)
        {
            if (!ModelState.IsValid)
            {
                return View(country);
            }

            if (_unitOfWork.Countries.Exist(country))
            {
                ModelState.AddModelError(string.Empty, "There already exists a country with that name.");

                return View(country);
            }

            _unitOfWork.Countries.Add(country);
            _unitOfWork.SaveChanges();

            TempData["SUCCESS"] = "Country added successfully";

            return RedirectToAction("Index");
        }

        #endregion

        #region EDIT

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            Country country = _unitOfWork.Countries.Get(c => c.CountryId == id);

            if (country is null)
            {
                return NotFound();
            }

            return View(country);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Country country)
        {
            if (!ModelState.IsValid)
            {
                return View(country);
            }

            if (_unitOfWork.Countries.Exist(country))
            {
                ModelState.AddModelError(string.Empty, "There already exists a country with that name.");

                return View(country);
            }

            _unitOfWork.Countries.Update(country);
            _unitOfWork.SaveChanges();

            TempData["SUCCESS"] = "Country edited successfully";

            return RedirectToAction("Index");
        }

        #endregion

        #region DELETE

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id is null || id == 0)
            {
                return NotFound();
            }

            Country country = _unitOfWork.Countries.Get(c => c.CountryId == id);

            if (country is null)
            {
                return NotFound();
            }

            if (_unitOfWork.Countries.ItsRelated(country))
            {
                TempData["ERROR"] = "Can't be deleted because it has related cities";

                return RedirectToAction("Index");
            }

            return View(country);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Country country)
        {
            if (!_unitOfWork.Countries.Exist(country.CountryId))
            {
                return NotFound();
            }
            else
            {
                _unitOfWork.Countries.Delete(country);
                _unitOfWork.SaveChanges();

                TempData["WARNING"] = "Country was deleted";

                return RedirectToAction("Index");
            }
        }



        #endregion

        #region API CALL

        [HttpGet]
        public IActionResult GetCountries()
        {
            var countries = _unitOfWork.Countries.GetAll();

            JsonSerializerOptions options = new JsonSerializerOptions()
            {
                PropertyNameCaseInsensitive = true
            };

            return Json( new { data = countries }, options);
        }

        [HttpDelete]
        public IActionResult DeleteCountry(int? id)
        {
            if (id is null || id <= 0)
            {
                return Json(new { success = false, message = "Not found" });
            }

            Country country = _unitOfWork.Countries.Get(c => c.CountryId == id);

            if (country is null)
            {
                return Json(new { success = false, message = "Not found" });
            }

            try
            {
                _unitOfWork.Countries.Delete(country);
                _unitOfWork.SaveChanges();

                return Json(new { success = true, message = "Country deleted successfully" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }

        }

        #endregion
    }
}

KMGamesCore.Web/Areas/Admin/Views/Countries/Create.cshtml
@using KMGamesCore.Models.Models

@model Country
@{
    ViewData["title"] = "Create";
}


<div class="container justify-content-center w-50 mt-5">
    <form method="post" asp-controller="Countries" asp-action="Create">
        <div class="shadow rounded-4 p-4">
            <h2>New Country</h2>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="form-label"></label>
                <input type="text" asp-for="Name" class="form-control w-50"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="d-flex justify-content-between mt-5">
            <button type="submit" class="btn btn-outline-primary w-25">
                <i class="bi bi-check2"></i>
            </button>
            <a asp-controller="Countries" asp-action="Index" class="btn btn-outline-danger w-25">
                <i class="bi bi-x-lg"></i>
            </a>
        </div>
    </form>
</div>
@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }

}

KMGamesCore.Web/Areas/Admin/Views/Countries/Delete.cshtml
@using KMGamesCore.Models.Models

@model Country
@{
    ViewData["title"] = "Delete";
}

<div class="container justify-content-center w-50  mt-5">
    <form asp-controller="Countries" asp-action="Delete">
        <div class="shadow bg-body rounded-4 p-4">
            <h2>Delete Country</h2>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="form-label"></label>
                <input type="text" asp-for="Name" disabled class="form-control w-50" />
                <span asp-validation-for="Name" class="text-danger"></span>

                @Html.HiddenFor(model => model.CountryId)
                @Html.HiddenFor(model => model.RowVersion)
            </div>
        </div>
        <div class="d-flex justify-content-between mt-5">
            <button type="submit" class="btn btn-outline-primary w-25">
                <i class="bi bi-check2"></i>
            </button>
            <a asp-controller="Countries" asp-action="Index" class="btn btn-outline-danger w-25">
                <i class="bi bi-x-lg"></i>
            </a>
        </div>
    </form>
</div>

KMGamesCore.Web/Areas/Admin/Views/Countries/Edit.cshtml
@using KMGamesCore.Models.Models
@model Country
@{
    ViewData["title"] = "Edit";
}

<div class="container justify-content-center w-50  mt-5">
    <form asp-controller="Countries" asp-action="Edit">
        <div class="shadow bg-body rounded-4 p-4">
            <h2>Edit Country</h2>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

@*              <input asp-for="CountryId" type="hidden"/>
                <input asp-for="RowVersion" type="hidden" />*@

                <label asp-for="Name" class="form-label"></label>
                <input type="text" asp-for="Name" class="form-control w-50"/>
                <span asp-validation-for="Name" class="text-danger"></span>

                @Html.HiddenFor(model => model.CountryId)
                @Html.HiddenFor(model => model.RowVersion)
            </div>
        </div>
        <div class="d-flex justify-content-between mt-5">
            <button type="submit" class="btn btn-outline-primary w-25">
                <i class="bi bi-check2"></i>
            </button>
            <a asp-controller="Countries" asp-action="Index" class="btn btn-outline-danger w-25">
                <i class="bi bi-x-lg"></i>
            </a>
        </div>
    </form>
</div>
@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }

}

KMGamesCore.Web/Areas/Admin/Views/Countries/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@using KMGamesCore.Models.Models
@model IEnumerable<Country>

@{
    ViewData["Title"] = "Index";
}


<div class="container-fluid justify-content-center w-75">
    <div class="d-block d-flex justify-content-between ">
        <h2>Countries</h2>
        <div>
            <a asp-controller="Countries" asp-action="Create" class="btn btn-outline-primary">
                <i class="bi bi-plus-lg"></i>
            </a>
        </div>
    </div>
    <div class="d-block">
        <table class="table">
            <thead>
                <tr class="table-primary">
                    <th>Country</th>
                    <th class="text-end">Actions</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                @foreach(Country country in Model)
                {
                    <tr class="table-dark">
                        <td valign="middle">@country.Name</td>
                        <td align="right">
                            <a asp-controller="Countries" asp-action="Edit" asp-route-id="@country.CountryId" 
                                class="btn btn-outline-warning rounded-circle pt-1 pb-1 pe-2 ps-2">
                                <i class="bi bi-brilliance"></i>
                            </a>
                            <a asp-controller="Countries" asp-action="Delete" asp-route-id="@country.CountryId" 
                                class="btn btn-outline-danger ms-2 rounded-circle pt-1 pb-1 pe-2 ps-2">
                                <i class="bi bi-x-lg"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

KMGamesCore.Web/Areas/Admin/Views/Countries/IndexDTable.cshtml
@using KMGamesCore.Models.Models
@model IEnumerable<Country>

@{
    ViewData["Title"] = "Index";
}


<div class="container-fluid justify-content-center w-75">
    <div class="d-block d-flex justify-content-between ">
        <h2>Countries</h2>
        <div>
            <a asp-controller="Countries" asp-action="Create" class="btn btn-outline-primary">
                <i class="bi bi-plus-lg"></i>
            </a>
        </div>
    </div>
    <div class="d-block">
        <table class="table" id="tblCountries">
            <thead>
                <tr class="table-primary">
                    <th>Country</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="table-group-divider table-dark">
            </tbody>
        </table>
    </div>
</div>
@section Scripts{
    <script src="~/js/countriesTable.js"></script>
}